### Registrar Usuário
POST https://aliceadonismobile.onrender.com/register HTTP/1.1
Content-Type: application/json 

{
        "name": "Alice",
        "email": "alicerodrigueslili.05@gmail.com",
        "password": "1234"
}


###Autenticar usuário

POST https://aliceadonismobile.onrender.com/login HTTP/1.1
Content-Type: application/json 

{
        "email": "alicerodrigueslili.05@gmail.com",
        "password": "1234"
}